
CREATE TABLE IF NOT EXISTS `books` (
    `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `author` VARCHAR(50) NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8 COLLATE utf8_general_ci;


# CREATE TABLE IF NOT EXISTS `authors` (
#     `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
#     `last_name` VARCHAR(50) NOT NULL,
#     `first_name` VARCHAR(50) NOT NULL,
#     `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
#     `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
# ) CHARACTER SET utf8 COLLATE utf8_general_ci;
#
# ALTER TABLE
#     `books`
#     ADD
#         FOREIGN KEY (`author_id`) REFERENCES `authors`(`id`);